### ISSUE TITLE
PSI-Mod

### ISSUE THREAD

**Issue by jallmer** [savastakan/dnmso#1]
PSI-Mod should be supported as primary reference. PSI-Mod-Ref is a member of Modification and all necessary information can be retrieved from PSI-Mod with that reference. 

1) The library needs to be able to read PSI-Mod and retrieve information associated with a term.
2) The library needs to be able to map previous ad hoc modification formats (PepNovo, Lutefisk, etc. to PSI-Mod using the name, amino acid, and mass shift.
3) The library should default to using PSI-Mod and only use the limited information in DNMSO Modifications when PSI-Mod access is not available. 

https://www.ebi.ac.uk/ols/ontologies/mod/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMOD_00000&viewMode=All&siblings=false

**Comment by jallmer** [comment]
@savastakan 
Can this be closed?

**Comment by savastakan** [comment]
yes, we can close
